merge PDF

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -10,6 +10,7 @@ on:
 #
 jobs:
   build:
+    permissions: write-all #for dependabot auto PR - create a test report
 
     # <!-- This is a YAML comment for use in annotated code examples. -->
     # You can run this workflow using a different operating systems.
@@ -31,45 +32,29 @@ jobs:
           java-version: '17'
           distribution: 'corretto'
       # The "Build with Maven" step runs the Maven `package` target in non-interactive mode to ensure that your code builds, tests pass, and a package can be created.
-      - name: Build with Maven
+      - name: Build with Maven and Test
         run: mvn clean install
 
       # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
-#      - name: Update dependency graph
-#        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
-#      - name: Publish Test Report
-#        uses: mikepenz/action-junit-report@v1
-#        if: success() || failure() # always run even if the previous step fails
-#        with:
-#          report_paths: '**/build/test-results/test/TEST-*.xml'
-#      - name: Run JUnit Tests
-#        run: mvn test
+      #      - name: Update dependency graph
+      #        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
+      #      - name: Publish Test Report
+      #        uses: mikepenz/action-junit-report@v1
+      #        if: success() || failure() # always run even if the previous step fails
+      #        with:
+      #          report_paths: '**/build/test-results/test/TEST-*.xml'
+      #      - name: Run JUnit Tests
+      #        run: mvn test
       - name: JUnit Test Report
-        uses: dorny/test-reporter@v1 #{owner}/{repository}@{ref}
+        uses: mikepenz/action-junit-report@v4
+        if: (success() || failure()) # always run even if the previous step fails
+        with:
+          report_paths: target/surefire-reports/*.xml
+      - name: JUnit Test Report #for analysis tests report as a table
+        uses: dorny/test-reporter@v1.7.0 #{owner}/{repository}@{ref}
         if: always()
         with:
           name: Maven Tests
           path: target/surefire-reports/*.xml
           reporter: java-junit
-          fail-on-error: true
-
-
-      - name: Generate build number
-        id: buildnumber
-        uses: einaregilsson/build-number@v3
-        with:
-          token: ${{secrets.github_token}}
-
-      # Now you can pass ${{ steps.buildnumber.outputs.build_number }} to the next steps.
-      - name: Another step as an example
-        uses: actions/hello-world-docker-action@v1
-        with:
-          who-to-greet: ${{ steps.buildnumber.outputs.build_number }}
-
-
-      - name: Output Run ID
-        run: echo ${{ github.run_id }}
-      - name: Output Run Number
-        run: echo ${{ github.run_number }}
-      - name: Output Run Attempt
-        run: echo ${{ github.run_attempt }}
+          fail-on-error: false
